project_id = "ttywuskboaranphxxgtr"

[functions.process-payout]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.create-merchant]
verify_jwt = false

[functions.payin]
verify_jwt = false

[functions.payout]
verify_jwt = false

[functions.get-payment-link-merchant]
verify_jwt = false

[functions.callback-handler]
verify_jwt = false

[functions.admin-update-merchant]
verify_jwt = false

[functions.payment-link-pay]
verify_jwt = false

[functions.send-telegram]
verify_jwt = false

[functions.telegram-bot]
verify_jwt = false

[functions.check-gateway-balance]
verify_jwt = false

[functions.daily-summary]
verify_jwt = false

[functions.export-database]
verify_jwt = false

[functions.server-health-monitor]
verify_jwt = false

[functions.verify-withdrawal-password]
verify_jwt = false

[functions.check-order-status]
verify_jwt = false
