project_id = "ttywuskboaranphxxgtr"

[functions.process-payout]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.create-merchant]
verify_jwt = false

[functions.payin]
verify_jwt = false

[functions.payout]
verify_jwt = false

[functions.get-payment-link-merchant]
verify_jwt = false

[functions.callback-handler]
verify_jwt = false

[functions.admin-update-merchant]
verify_jwt = false

[functions.payment-link-pay]
verify_jwt = false